In [1]:
import tensorflow as tf

# Declaring variables

In [2]:
# Declaring a variable
# var_name = tf.Variable(<value>,tf.<datatype_name>)

string = tf.Variable("This is a string",tf.string)
number = tf.Variable(123,tf.int64)
floating  = tf.Variable(123.43,tf.float64) 

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-12-14 19:48:32.546470: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-12-14 19:48:32.546586: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


# Ranking of tensors

In [3]:
# Rank of a tensor displays the dimensions of tensor

rank1_tensor = tf.Variable(['a','as'],tf.string)
rank2_tensor = tf.Variable([['a','r','er'],['e','rt','ji'],['e','rt','ji']],tf.string)

In [4]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shapes of a tensor
It shows amount of attributes in each dimension

In [5]:
rank2_tensor.shape 

TensorShape([3, 3])

Changing shape of tensor

In [6]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2, [3,-1]) # -1 tells to calculate the size of the dimensions in the place .
                                        #This will reshape the tensor to [3,3]
                                        # The number of elements in reshape must match the original

In [7]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Types of tensors
-> Constant
-> Variable
-> Placeholder
-> SparceTensor. All the tensor value cannot be changed during execution except "Variable"

# Evaluating the tensors

In [8]:
with tf.Session() as secc: # Creates a session using default graph
    tensor1.eval() #<tensor_name>.eval() 