# Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]],np.int64)

In [3]:
myarr[0]

array([ 3,  6, 32,  7])

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr[0,1]

6

# Array creation using numpy

In [6]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
listarray.dtype

dtype('int64')

In [9]:
listarray.size

9

In [10]:
listarray.shape

(3, 3)

In [11]:
zeros = np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
rng = np.arange(15)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
lspace = np.linspace(1,4,4) #np.linspace(first element,last element,spacing)

In [16]:
lspace

array([1., 2., 3., 4.])

In [17]:
emp = np.empty((4,6))

In [18]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
emp_like = np.empty_like(lspace)

In [20]:
emp_like

array([1., 2., 3., 4.])

In [21]:
ide = np.identity(45) #identity matrix

In [22]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
ide.shape

(45, 45)

In [24]:
arr = np.arange(99)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
arr = arr.reshape(3,33)

In [27]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr = arr.ravel()

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.shape

(99,)

In [31]:
x = np.arange(9)

In [32]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
x = x.reshape(3,3)

In [34]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
ar = np.array(x)

In [36]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
ar.sum(axis = 0)

array([ 9, 12, 15])

In [38]:
ar.sum(axis = 1)

array([ 3, 12, 21])

In [39]:
ar.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [40]:
ar.flat

In [41]:
for i in ar.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [42]:
ar.ndim

2

In [43]:
ar.size

9

In [44]:
ar.nbytes

72

In [45]:
one = np.array([1,34,26,34,6543,23,])

In [46]:
one.argmax() #returns index of max element

4

In [47]:
one.argmin() #returns index of min element

0

In [48]:
one.argsort() #returns index of sorted elements 

array([0, 5, 2, 1, 3, 4])

In [49]:
ar.argmax()

8

In [50]:
ar.argmax(axis=0)

array([2, 2, 2])

In [51]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [52]:
ar.argsort(axis = 0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [53]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [55]:
 ar*ar2   #can perform arthematic operations for arrays,lists and more

array([[ 0,  2,  2],
       [12,  0, 30],
       [48,  7,  0]])

In [56]:
np.sqrt(ar)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [57]:
ar.sum()

36

In [58]:
ar.max()

8

In [59]:
ar.min()

0

In [60]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
np.where(ar>5) #returns index of given condition

(array([2, 2, 2]), array([0, 1, 2]))

In [62]:
np.count_nonzero(ar)

8

In [63]:
np.nonzero(ar)

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))

In [64]:
import sys

In [65]:
py_ar = [0,4,55,2]

In [67]:
np_ar = np.array(py_ar)

In [68]:
sys.getsizeof(1)*len(py_ar)

112

In [69]:
np_ar.itemsize*np_ar.size

32